### ISSUE TITLE
/usr/node/ttnode: 无法执行二进制文件

### ISSUE THREAD

**Issue by kangjinwen** [ShallowAi/ttnode_docker#1]
=======================================================
直接执行install_base.sh最后报错:
-----------------------------------------------------------------------------
[INFO] 开始运行甜糖星愿服务.
install_base.sh:行83: /usr/node/ttnode: 无法执行二进制文件
No input data.
=======================================================

大佬,运行环境是vm里的centos7,
docker里运行dockerfile :  docker build -t centosttnode:1 /usr/DockerTianTang
-----------------------------------------------------------------------------
Step 2/5 : LABEL maintainer="mrkang007@qq.com"
 ---> [Warning] The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested
 ---> Running in 7440fbd75a92
Removing intermediate container 7440fbd75a92
 ---> 13374c5315a6
Step 3/5 : COPY entry.sh install_base.sh /
 ---> 634458053ebd
Step 4/5 : RUN sh install_base.sh
 ---> [Warning] The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested
 ---> Running in 685d3953d0b2
standard_init_linux.go:219: exec user process caused: exec format error
The command '/bin/sh -c sh install_base.sh' returned a non-zero code: 1
==================================================

**Comment by ShallowAi** [comment]
github上该文件尚未更新
具体请见dockerhub已构建镜像，近期更新。

另外在x86模式下需要额外运行一个qemu-user-static作为转换
